name: Watchdog
on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Annuler les runs précédents du bot
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Relancer le bot
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: restart-bot